name: test

#on:
#  workflow_dispatch:

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 코드
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set ENVs
        run: |
          echo "current_date=$(date +"%Y%m%d")" >> $GITHUB_ENV
          echo "PROJECT_NAME=DEMO_APP" >> $GITHUB_ENV


      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: copy files
        run: |
          if [ ! -d ./deploy ]; then
            mkdir ./deploy
          fi
          cp ./build/libs/*.jar ./deploy
          cp appspec.yml ./deploy
          cp -r scripts/ ./deploy

      - name: Zip Files
        run: |
          zip -r "${PROJECT_NAME}_${current_date}.zip" ./deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME}}
        run: |
          aws s3 cp \
          "${PROJECT_NAME}_${current_date}.zip" s3://$BUCKET_NAME/deploy_test/

      - name: Code Deploy
        run: aws deploy create-deployment --application-name ${{ secrets.CODE_DEPLOY_APP_NAME }}
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name ${{ secrets.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }}
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},bundleType=zip,key=deploy_test/"${PROJECT_NAME}_${current_date}.zip"
